### ISSUE TITLE
Reference-Numbers

### ISSUE THREAD

**Issue by thomaskien** [iZettle/URL-Scheme#11]
It  would be great if the app would pass the iZettle-Payment-ID. The Software we want to integrate the iZettle-API in is creating the payment-id *after* a successful payment, that's after iZettle succeeded...
if a ID would be provided there would be no need to create a new ID, write it into the payment-subject, and add it later into our system to match the payment...

**Comment by mattiasjahnke** [comment]
Hi @thomaskien 

Perhaps I've partially answered this already in your other issue, but anyway:

The reason we've designed the URL-scheme so that the integrator provides us with a reference, rather than the other way around is because if the either of the apps (iZettle or 3rd party) crash, or there's any sorts or error along the way, the integrators knows about a reference that can be used to query the state of the payment.

My suggestion (even though you posted your question quite some time ago) is that you provide a reference to the iZettle payment, and when the payment is successful you match that reference with the payment-id created by the software.
