### ISSUE TITLE
reference broken in 4.3.0

### ISSUE THREAD

**Issue by thomaskien** [iZettle/URL-Scheme#15]
Hey!

The subject/reference/title/whatever is broken in the current version 4.3.0.
I tried both: referralCode and reference, but izettle always shows something like "manual payment" online.
It was working till 25.10.2015 using the predescessor-version... (still using the old url-scheme).

BTW: is the api-key not existent any more? not reflected in the documentation right now...

Here you see my URL wich works for payment but nothing more:

izettle://api/payment/charge?enforcedUserAccount=bla@bla.de&api-key=xxxxx&reference=13141446669675&amount=2&referralCode=13141446669675&currency=EUR&failureURL=blabla.php&successURL=bla.php

Do you have any idea?

Regards from Aachen,

Thomas

**Comment by mattiasjahnke** [comment]
Hey @thomaskien 

**Regarding the reference**
This is recent change in our system (not specific to version 4.3 of iZettle). The reference-as-product-name logic (that's now changed) was primarily for older versions of the URL scheme that's deprecated.

We'll investigate how to handle the references for older versions of the URL scheme going forward since the app still supports them, but we encourage our integrators to use the latest version that's described in this github repository.

For the new version of the URL scheme, we expect the integrators to use `reference` when triggering a payment, then keep a track of the references and their outcomes, and if needed - query iZettle to lookup an outcome of a payment with a given `reference` (https://github.com/iZettle/URL-Scheme/#query-for-paymentinfo) or do a refund (https://github.com/iZettle/URL-Scheme/#refund-payment)

**Regarding the API-key**
Yes you're right - the API-key is no longer required for the URL-scheme.

**Comment by thomaskien** [comment]
Hi Mattias!

After 2nd of November izettle was broken using the old urls (was working since 2013 like that). it was revived using the new URL scheme 3.0. If api-key really is ignored now the enforcedUserAccount seems to be mandatory - without both it always prompted for login after izettle opened.

We use reference as suggested, exacly like that our payment-system works. But the reference no longer appears online in the payment-view on izettle. Out reference is userID + unix-time of payment-start. Last time it was set as product-name 25. of october, 27th it did not work any more (since then it shows "Manueller Betrag" as product name). Our code was first changed yesterday -- it looks like you want the old scheme to be supported but in real it is broken?

Perhaps the problem is only in the web-interface? If i export excel I get the identifier, jeha! ;-)

Thank's for your help, since i found the needed data in the excel-export i am happy enough now!

Regards from Aachen,

Thomas
