### ISSUE TITLE
Is there an Android version of the iZettle API?

### ISSUE THREAD

**Issue by HNygard** [iZettle/URL-Scheme#7]
Is there an Android version of the API?
Maybe a hidden Android intent somewhere?

**Comment by crisdo98** [comment]
Hi @joezorry, how's that android sdk looking now?

**Comment by joezorry** [comment]
@crisdo98 thx for asking. We are currently working on the SDK, but it's in early stages yet and we'll see when it comes, but it's in progress and I will inform you once we are in a bit more stable state. :+1: 
Exciting times! :smiley:

**Comment by Oliveirax** [comment]
Hi. I've built an app for a client in iOS with izettle integration, it worked beautifully. Now, the same client asked for an android version. Is it true that no SDK is available? what about calling the izettle app through an android intent and receiving the result transaction result through the same intent?

**Comment by Gruneau** [comment]
@Oliveirax The SDK is still under development. And as you wrote, you will create an intent and receive the result on callback `onActivityResult`.

**Comment by HNygard** [comment]
@Gruneau : For over 2 years? Great.

**Comment by Oliveirax** [comment]
@Gruneau: Are you saying that, Currently, I cannot call the izettle app (the current one, available in playstore) through an intent and get the result? Not even that is possible?

**Comment by Gruneau** [comment]
@Oliveirax correct

@HNygard We understand that it is frustrating to wait for an SDK this long, however we've had to prioritise other stuff as well.

**Comment by fl0pp** [comment]
You have a great product, but I am disappointed about the prioritization. Looking forward to this feature! Arrange a hackaton and I will buy you a beer! :)

**Comment by jontesehlin** [comment]
Any news on the Android API?

**Comment by joezorry** [comment]
Agree with @fl0pp a iZettle hackathon would be awesome.

**Comment by SofiaCarlander** [comment]
Sorry guys, the Android SDK will take some more time. We have a lot to work on and are limited numbers of Android developers. We are working (and recruiting) as fast as we can. Please have patience, and we will arrange a hackathon when it's done :-)

**Comment by HNygard** [comment]
@SofiaCarlander : We are coming up on the third year now....

Adding an Android intent should be fairly strait forward and should not take this much time. It will open up a lot of possibilities for others to use iZettle as payment platform in Android as well as iOS.

---

And for everybody else: Please apply for the position @SofiaCarlander mention at iZettle so they can get some help with this:
http://www.izettle.com/no/jobs/oktc1fwK

**Comment by mahomedalid** [comment]
Why is closed?

**Comment by Oliveirax** [comment]
I did not fully understand. #7 is closed... Does this mean the izettle android api is avaliable? Where can I get it?

**Comment by ninohoglund** [comment]
There is currently no android SDK. Please sign up for updates here: http://developer.izettle.com 
This repository is about the URL scheme, currently only supported on iOS.

**Comment by HNygard** [comment]
@ninohoglund : Well. That is just stupid. Fix the issue instead. You guys have an Android team. Set them to work.

@SofiaCarlander : Why are you closing the issue?

**Comment by Oliveirax** [comment]
I don't fully understand your strategy. Izettle is a wonderful device. And the ios api is beautiful. As I said before, after the iOS implementation, my client needed the izettle for android. It was not available. I was forced to adopt the sumup terminal and remake the ios app, in order to support both ios and android, I must say that it was a downgrade, but at least it is compatible with both platforms.

**Comment by teicher** [comment]
So if you close this issue because "it's about URL scheme", please link to the issue that is the real issue for "Please provide Android version of the iZettle API", so people can star it and comment on it.

I signed up for "Developer SDK for Android. We're hard at work on this still, but please leave your email if you'd like early access." on your website some months ago, and thought well, okay, might take a couple of months. I am quite shocked to learn now that it's been "taking 3 years now" (for doing nothing...?) - are you sure that there is any progress at all, or is all that just a red herring ?

**Comment by djmj** [comment]
Not supporting android API is a show stopper. Is there a mobile-web integration at least? 

Competition payleven and sump support android and mobile-web. We would like to use izettle, but without android API, we of cause will go to competition.

**Comment by mansbernhardt** [comment]
@djmj: You might consider integrating with several providers and let your customer choose. Many of our integrators have successfully integrated our SDK in less than a day.

**Comment by mansbernhardt** [comment]
I also want to point out the the URL-Scheme has been deprecated and we recommend doing a full integration using our SDK instead: https://github.com/iZettle/sdk-ios

**Comment by teicher** [comment]
Hello!? This is about Android, not iOS.
Please get a coffee before posting.

**Comment by mansbernhardt** [comment]
@teicher Not sure why you are being rude here? I suggested that instead of not supporting iZettle SDK because of the lack of Android support, you could still support it for iOS as well as supporting other third party payment solutions that also covers Android (or is Android only). I'm not sure why you say this is an irrelevant response to @djmj comment?

**Comment by teicher** [comment]
Not meaning being rude here, should've put a smilie with the coffee.

Anyway, but, since Android SDK is being promised for 3 years now (see right column here https://www.izettle.com/de/developer ) - but it seems nothing whatsoever is happening - it's maybe a bit disappointing being recommended to use something else now.

(And yes, we've integrated our Android-Only App with SumUp in maybe a day.)

**Comment by djmj** [comment]
@mansbernhardt Yes you are right to integrate our shop system with multiple providers. But we currently choose to provide an android app (hybrid with mobile web page shown), because we have control of the handheld devices they will use (it will include a barcode scanner).

**Comment by vladdeSV** [comment]
Leaving a note here that I too wish for an Android SDK

**Comment by bengosney** [comment]
5 years and still no Android API?

**Comment by joezorry** [comment]
@bengosney
and other people following this thread or coming here from a google search.
I would suggest that people following this thread to mail integrations@izettle.com
So iZettle can see how big the interest actually is for an Android SDK, if the interest is not big it's not going to happen.

If iZettle see bigger interest in it will have more chance of happening.

PA: I work for iZettle as an android developer, however these are my own personal opinion and does not reflect iZettle as a whole. :P

**Comment by fl0pp** [comment]
Email sent

**Comment by vladdeSV** [comment]
Sent an email

**Comment by fl0pp** [comment]
An alternative to iZettle is https://sumup.com. They have SDK for both Android and iOS. I have yet to test it out.

**Comment by MinuteBar** [comment]
Also thinking here to move to SumUp for the Android SDK

**Comment by ewookscorp** [comment]
Well I use SumUP since they have Andorid SDK. How hard to be add similar URI call to iZettle like in SumUP?

**Comment by Shadowstyler** [comment]
Sumup is a good alternative, althou I have had lots of client complains about their payment device disconnect at random intervals. There seems to be a problem with bluetooth no reconnecting properly.

**Comment by DinoKev** [comment]
Any updates on the progress of android SDK?

**Comment by ewookscorp** [comment]
2020 and still NO Android API???? We need at least URL-Scheme intent api for iZettle.
